import type { BentoTemplate } from '../types'

export const boldTemplate: BentoTemplate = {
  id: 'bold',
  name: 'Bold',
  description: 'Photo-forward, dramatic layout with full-width hero gallery photo',
  variants: {
    full: {
      slots: [
        { id: 'photo1', areaName: 'photo1', type: 'photo' },
        { id: 'about', areaName: 'about', type: 'about' },
        { id: 'contact', areaName: 'contact', type: 'contact' },
        { id: 'cv', areaName: 'cv', type: 'cv' },
        { id: 'photo2', areaName: 'photo2', type: 'photo' },
        { id: 'photo3', areaName: 'photo3', type: 'photo' },
        { id: 'experience', areaName: 'exp', type: 'experience' },
        { id: 'endorsements', areaName: 'endorse', type: 'endorsements' },
        { id: 'certs', areaName: 'certs', type: 'certifications' },
        { id: 'stats', areaName: 'stats', type: 'stats' },
        { id: 'photo4', areaName: 'photo4', type: 'photo' },
        { id: 'photo5', areaName: 'photo5', type: 'photo' },
        { id: 'education', areaName: 'edu', type: 'education' },
        { id: 'skills', areaName: 'skills', type: 'skills' },
      ],
      areas: {
        desktop: [
          '"photo1  photo1  photo1  photo1"',
          '"photo1  photo1  photo1  photo1"',
          '"about   about   contact cv"',
          '"photo2  photo3  exp     exp"',
          '"photo2  photo3  exp     exp"',
          '"endorse endorse certs   stats"',
          '"photo4  photo5  more    more"',
          '"edu     edu     skills  skills"',
        ].join('\n'),
        mobile: [
          '"photo1  photo1"',
          '"photo1  photo1"',
          '"about   about"',
          '"contact cv"',
          '"exp     exp"',
          '"photo2  photo3"',
          '"endorse endorse"',
          '"certs   stats"',
          '"photo4  photo5"',
          '"edu     edu"',
          '"skills  skills"',
          '"more    more"',
        ].join('\n'),
      },
    },
    medium: {
      slots: [
        { id: 'photo1', areaName: 'photo1', type: 'photo' },
        { id: 'about', areaName: 'about', type: 'about' },
        { id: 'contact', areaName: 'contact', type: 'contact' },
        { id: 'cv', areaName: 'cv', type: 'cv' },
        { id: 'experience', areaName: 'exp', type: 'experience' },
        { id: 'photo2', areaName: 'photo2', type: 'photo' },
        { id: 'endorsements', areaName: 'endorse', type: 'endorsements' },
        { id: 'certs', areaName: 'certs', type: 'certifications' },
        { id: 'education', areaName: 'edu', type: 'education' },
        { id: 'skills', areaName: 'skills', type: 'skills' },
      ],
      areas: {
        desktop: [
          '"photo1  photo1  photo1  photo1"',
          '"photo1  photo1  photo1  photo1"',
          '"about   about   contact cv"',
          '"exp     exp     photo2  photo2"',
          '"endorse endorse certs   certs"',
          '"edu     edu     skills  skills"',
        ].join('\n'),
        mobile: [
          '"photo1  photo1"',
          '"photo1  photo1"',
          '"about   about"',
          '"contact cv"',
          '"exp     exp"',
          '"photo2  photo2"',
          '"endorse endorse"',
          '"certs   certs"',
          '"edu     edu"',
          '"skills  skills"',
        ].join('\n'),
      },
    },
    minimal: {
      slots: [
        { id: 'photo1', areaName: 'photo1', type: 'photo' },
        { id: 'about', areaName: 'about', type: 'about' },
        { id: 'contact', areaName: 'contact', type: 'contact' },
        { id: 'cv', areaName: 'cv', type: 'cv' },
        { id: 'experience', areaName: 'exp', type: 'experience' },
        { id: 'education', areaName: 'edu', type: 'education' },
        { id: 'skills', areaName: 'skills', type: 'skills' },
      ],
      areas: {
        desktop: [
          '"photo1  photo1  photo1  photo1"',
          '"about   about   contact cv"',
          '"exp     exp     edu     edu"',
          '"skills  skills  skills  skills"',
        ].join('\n'),
        mobile: [
          '"photo1  photo1"',
          '"about   about"',
          '"contact cv"',
          '"exp     exp"',
          '"edu     edu"',
          '"skills  skills"',
        ].join('\n'),
      },
    },
  },
}
