import type { BentoTemplate } from '../types'

export const classicTemplate: BentoTemplate = {
  id: 'classic',
  name: 'Classic',
  description: 'Balanced, editorial layout with alternating photo and content tiles',
  variants: {
    full: {
      slots: [
        { id: 'photo1', areaName: 'photo1', type: 'photo' },
        { id: 'about', areaName: 'about', type: 'about' },
        { id: 'contact', areaName: 'contact', type: 'contact' },
        { id: 'cv', areaName: 'cv', type: 'cv' },
        { id: 'photo2', areaName: 'photo2', type: 'photo' },
        { id: 'experience', areaName: 'exp', type: 'experience' },
        { id: 'photo3', areaName: 'photo3', type: 'photo' },
        { id: 'certs', areaName: 'certs', type: 'certifications' },
        { id: 'stats', areaName: 'stats', type: 'stats' },
        { id: 'endorsements', areaName: 'endorse', type: 'endorsements' },
        { id: 'photo4', areaName: 'photo4', type: 'photo' },
        { id: 'education', areaName: 'edu', type: 'education' },
        { id: 'skills', areaName: 'skills', type: 'skills' },
        { id: 'photo5', areaName: 'photo5', type: 'photo' },
      ],
      areas: {
        desktop: [
          '"photo1  photo1  about   about"',
          '"photo1  photo1  about   about"',
          '"contact cv      photo2  photo2"',
          '"exp     exp     photo3  photo3"',
          '"exp     exp     photo3  photo3"',
          '"certs   stats   endorse endorse"',
          '"photo4  photo4  edu     edu"',
          '"skills  skills  photo5  more"',
        ].join('\n'),
        mobile: [
          '"photo1  photo1"',
          '"about   about"',
          '"contact cv"',
          '"exp     exp"',
          '"photo2  photo3"',
          '"endorse endorse"',
          '"certs   stats"',
          '"edu     edu"',
          '"photo4  photo5"',
          '"skills  skills"',
          '"more    more"',
        ].join('\n'),
      },
    },
    medium: {
      slots: [
        { id: 'photo1', areaName: 'photo1', type: 'photo' },
        { id: 'about', areaName: 'about', type: 'about' },
        { id: 'contact', areaName: 'contact', type: 'contact' },
        { id: 'cv', areaName: 'cv', type: 'cv' },
        { id: 'experience', areaName: 'exp', type: 'experience' },
        { id: 'photo2', areaName: 'photo2', type: 'photo' },
        { id: 'certs', areaName: 'certs', type: 'certifications' },
        { id: 'endorsements', areaName: 'endorse', type: 'endorsements' },
        { id: 'education', areaName: 'edu', type: 'education' },
        { id: 'skills', areaName: 'skills', type: 'skills' },
      ],
      areas: {
        desktop: [
          '"photo1  photo1  about   about"',
          '"photo1  photo1  about   about"',
          '"contact cv      exp     exp"',
          '"photo2  photo2  exp     exp"',
          '"certs   endorse endorse endorse"',
          '"edu     edu     skills  skills"',
        ].join('\n'),
        mobile: [
          '"photo1  photo1"',
          '"about   about"',
          '"contact cv"',
          '"exp     exp"',
          '"photo2  photo2"',
          '"endorse endorse"',
          '"certs   certs"',
          '"edu     edu"',
          '"skills  skills"',
        ].join('\n'),
      },
    },
    minimal: {
      slots: [
        { id: 'photo1', areaName: 'photo1', type: 'photo' },
        { id: 'about', areaName: 'about', type: 'about' },
        { id: 'contact', areaName: 'contact', type: 'contact' },
        { id: 'cv', areaName: 'cv', type: 'cv' },
        { id: 'experience', areaName: 'exp', type: 'experience' },
        { id: 'education', areaName: 'edu', type: 'education' },
        { id: 'skills', areaName: 'skills', type: 'skills' },
      ],
      areas: {
        desktop: [
          '"photo1  photo1  about   about"',
          '"contact cv      exp     exp"',
          '"edu     edu     skills  skills"',
        ].join('\n'),
        mobile: [
          '"photo1  photo1"',
          '"about   about"',
          '"contact cv"',
          '"exp     exp"',
          '"edu     edu"',
          '"skills  skills"',
        ].join('\n'),
      },
    },
  },
}
