import type { BentoTemplate } from '../types'

export const classicTemplate: BentoTemplate = {
  id: 'classic',
  name: 'Classic',
  description: 'Balanced, editorial layout with alternating photo and content tiles',
  variants: {
    full: {
      slots: [
        { id: 'stats', areaName: 'stats', type: 'stats' },
        { id: 'about', areaName: 'about', type: 'about' },
        { id: 'photo1', areaName: 'photo1', type: 'photo' },
        { id: 'experience', areaName: 'exp', type: 'experience' },
        { id: 'photo2', areaName: 'photo2', type: 'photo' },
        { id: 'endorsements', areaName: 'endorse', type: 'endorsements' },
        { id: 'certs', areaName: 'certs', type: 'certifications' },
        { id: 'photo3', areaName: 'photo3', type: 'photo' },
        { id: 'education', areaName: 'edu', type: 'education' },
        { id: 'photo4', areaName: 'photo4', type: 'photo' },
        { id: 'skills', areaName: 'skills', type: 'skills' },
        { id: 'hobbies', areaName: 'hobbies', type: 'hobbies' },
        { id: 'photo5', areaName: 'photo5', type: 'photo' },
      ],
      areas: {
        desktop: [
          '"stats   stats   stats   stats"',
          '"about   about   photo1  photo1"',
          '"about   about   photo1  photo1"',
          '"exp     exp     photo2  photo2"',
          '"exp     exp     photo2  photo2"',
          '"endorse endorse photo3  photo3"',
          '"endorse endorse photo3  photo3"',
          '"certs   certs   certs   certs"',
          '"edu     edu     photo4  photo4"',
          '"photo5  photo5  photo4  photo4"',
          '"skills  skills  hobbies hobbies"',
        ].join('\n'),
        mobile: [
          '"stats   stats"',
          '"about   about"',
          '"exp     exp"',
          '"photo1  photo2"',
          '"endorse endorse"',
          '"endorse endorse"',
          '"certs   certs"',
          '"stats   stats"',
          '"photo3  photo3"',
          '"edu     edu"',
          '"photo4  photo5"',
          '"skills  skills"',
          '"hobbies hobbies"',
        ].join('\n'),
      },
    },
    medium: {
      slots: [
        { id: 'about', areaName: 'about', type: 'about' },
        { id: 'contact', areaName: 'contact', type: 'contact' },
        { id: 'cv', areaName: 'cv', type: 'cv' },
        { id: 'experience', areaName: 'exp', type: 'experience' },
        { id: 'photo1', areaName: 'photo1', type: 'photo' },
        { id: 'endorsements', areaName: 'endorse', type: 'endorsements' },
        { id: 'certs', areaName: 'certs', type: 'certifications' },
        { id: 'photo2', areaName: 'photo2', type: 'photo' },
        { id: 'education', areaName: 'edu', type: 'education' },
        { id: 'skills', areaName: 'skills', type: 'skills' },
      ],
      areas: {
        desktop: [
          '"about   about   contact cv"',
          '"about   about   exp     exp"',
          '"photo1  photo1  exp     exp"',
          '"endorse endorse certs   certs"',
          '"photo2  photo2  edu     edu"',
          '"skills  skills  skills  skills"',
        ].join('\n'),
        mobile: [
          '"about   about"',
          '"contact cv"',
          '"exp     exp"',
          '"photo1  photo1"',
          '"endorse endorse"',
          '"certs   certs"',
          '"photo2  photo2"',
          '"edu     edu"',
          '"skills  skills"',
        ].join('\n'),
      },
    },
    minimal: {
      slots: [
        { id: 'about', areaName: 'about', type: 'about' },
        { id: 'contact', areaName: 'contact', type: 'contact' },
        { id: 'cv', areaName: 'cv', type: 'cv' },
        { id: 'experience', areaName: 'exp', type: 'experience' },
        { id: 'photo1', areaName: 'photo1', type: 'photo' },
        { id: 'education', areaName: 'edu', type: 'education' },
        { id: 'skills', areaName: 'skills', type: 'skills' },
      ],
      areas: {
        desktop: [
          '"about   about   contact cv"',
          '"exp     exp     photo1  photo1"',
          '"edu     edu     skills  skills"',
        ].join('\n'),
        mobile: [
          '"about   about"',
          '"contact cv"',
          '"exp     exp"',
          '"photo1  photo1"',
          '"edu     edu"',
          '"skills  skills"',
        ].join('\n'),
      },
    },
  },
}
